user1 = User.create!(username: "steve", email: "thefirststevedave@gmail.com", phone_number: "5516554201", password: "password")
user2 = User.create!(username: "steve2", email: "thesecondstevedave@gmail.com", password: "password")
user3 = User.create!(username: "steve3", email: "thethirdstevedave@gmail.com", phone_number: "4155598988", password: "password")
user4 = User.create!(username: "mattgaryjoe", email: "mattgaryjoe@gmail.com", phone_number: "9175547210", password: "password")

broadcast1 = Broadcast.create!(topic: "The State of the Onion", speaker_id: 1, datetime: DateTime.new(2016,4,8,19,00) )
broadcast2 = Broadcast.create!(topic: "Rails Magic and How to Use It", speaker_id: 1, datetime: DateTime.new(2016,4,8,19,00) )
broadcast3 = Broadcast.create!(topic: "The Secrets of the Rails Wizards", speaker_id: 1, datetime: DateTime.new(2016,4,8,19,00))
broadcast4 = Broadcast.create!(topic: "Beware the Coming of the Nice Age", speaker_id: 4, datetime: DateTime.new(2016,4,8,19,00))
broadcast5 = Broadcast.create!(topic: "MarioKart Racers: Where Are They Now?", speaker_id: 4, datetime: DateTime.new(2016,4,8,19,00))
broadcast6 = Broadcast.create!(topic: "Google and Waze", speaker_id: 1, datetime: DateTime.new(2016,4,8,19,00))
broadcast7 = Broadcast.create!(topic: "Public Speaking", speaker_id: 1, datetime: DateTime.new(2016,4,8,19,00) )
broadcast8 = Broadcast.create!(topic: "Semi-private Speaking", speaker_id: 1, datetime: DateTime.new(2016,4,8,18,00))
broadcast9 = Broadcast.create!(topic: "TBD", speaker_id: 4, datetime: DateTime.new(2016,4,8,17,00))
broadcast10 = Broadcast.create!(topic: "TBA", speaker_id: 4, datetime: DateTime.new(2016,4,8,16,00))


ReminderSetting.create!(user_id: 2, broadcast_id: 1)
ReminderSetting.create!(user_id: 3, broadcast_id: 1, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 4, broadcast_id: 1, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 2)
ReminderSetting.create!(user_id: 3, broadcast_id: 2, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 4, broadcast_id: 2, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 3)
ReminderSetting.create!(user_id: 3, broadcast_id: 3, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 4, broadcast_id: 3, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 1, broadcast_id: 4, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 4)
ReminderSetting.create!(user_id: 3, broadcast_id: 4, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 1, broadcast_id: 5, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 5)
ReminderSetting.create!(user_id: 3, broadcast_id: 5, email_reminder: true, text_message: true)


ReminderSetting.create!(user_id: 2, broadcast_id: 6)
ReminderSetting.create!(user_id: 3, broadcast_id: 6, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 4, broadcast_id: 6, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 7)
ReminderSetting.create!(user_id: 3, broadcast_id: 7, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 4, broadcast_id: 7, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 8)
ReminderSetting.create!(user_id: 3, broadcast_id: 8, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 4, broadcast_id: 8, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 1, broadcast_id: 9, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 9)
ReminderSetting.create!(user_id: 3, broadcast_id: 9, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 1, broadcast_id: 10, email_reminder: true, text_message: true)
ReminderSetting.create!(user_id: 2, broadcast_id: 10)
ReminderSetting.create!(user_id: 3, broadcast_id: 10, email_reminder: true, text_message: true)
